import type { Metadata } from "next";
import { Outfit, Playwrite_GB_S } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
});

/** Google Fonts specimen: "Playwrite England SemiJoined" — family key `Playwrite GB S`. */
const playwriteLogo = Playwrite_GB_S({
  variable: "--font-logo",
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${playwriteLogo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
